### ISSUE TITLE
Цифровой домофон 

### ISSUE THREAD

**Issue by mksmo** [SCratORS/SmartIntercom#1]
Добрый день! Плата с цифровым домофоном Laskomex заработает?
![1BCAC541-D922-45D3-96DD-3441368F7A34](https://user-images.githubusercontent.com/4104873/115982375-30170780-a5a3-11eb-8c66-22acc529247d.jpeg)

![B3890DC9-B8AF-47B3-AE85-D30B7BA1FA78](https://user-images.githubusercontent.com/4104873/115982424-8c7a2700-a5a3-11eb-8a9f-6b0d546f125b.jpeg)

![F503653D-8980-46AA-A70C-BCA6C405C404](https://user-images.githubusercontent.com/4104873/115982433-a7e53200-a5a3-11eb-855e-0eb3dcc5e46c.jpeg)

**Comment by SCratORS** [comment]
Скорее всего нет

**Comment by AlexSZbrn** [comment]
99,9999% - нет. Даже не определится головным блоком.

**Comment by mksmo** [comment]
Эх…
