### ISSUE TITLE
Настройки не сохраняются

### ISSUE THREAD

**Issue by almirus** [SCratORS/SmartIntercom#13]
Похоже, когда обновляется ESPHome интеграция в HomeAssistan, то сбрасываются настройки, например, у меня не подключена трубка домофона, и после автообновления, домофон не открывается для курьера с ошибкой Error на дисплее, а потом оказывается что smartintercom_phone_disable=false как и светодиод и проигрывание звука.
Галочку ставил, Save нажимал, но не помогает

**Comment by SCratORS** [comment]
Да, есть такое. Обновление для ESP8266 уже выложены
