### ISSUE TITLE
Заюзать UART

### ISSUE THREAD

**Issue by almirus** [SCratORS/SmartIntercom#14]
Здравствуйте! Можно ли заюзать на платке с ESP8266 GPIO1 и GPIO3, подпаятся к ним? хочу с датчиком приближения совместить HLK-LD2410? потянет?

**Comment by SCratORS** [comment]
Приветствую!
GPIO3 нет, он работает с аудиотрактом.
GPIO1 занят на external_button, но можно юзать по своему желанию.
