### ISSUE TITLE
Вопросы и пожелания

### ISSUE THREAD

**Issue by Tehnik053** [SCratORS/SmartIntercom#2]
Можно ли узнать функции данного устройства? Так же хотелось бы увидеть хотя бы краткое видео устройства в работе. И для людей не использующих НА была бы очень полезна поддержка mqtt, тогда мы могли бы использовать это чудо устройство с другими умными домами. Я могу подключить это чудо устройство к аналоговому домофону?

**Comment by SCratORS** [comment]
Поддержку MQTT добавить легко.
Функции: открывание двери,  сброс, воспроизведение аудио файла на блок вызова.
Работает только с простыми координатными домофонами.
Статья и видео пример работы: https://pikabu.ru/story/domofon_na_esp_8140357

**Comment by Tehnik053** [comment]
Благодарю за ссылку и разъяснения. Mqtt многим было бы полезно,  очень жду его поддержки и заказываю платы)

**Comment by SCratORS** [comment]
Поддержка mqtt добавляется согласно этой статьи:
https://esphome.io/components/mqtt.html
т.е. фактически вписыванием настроек своего брокера.

**Comment by Tehnik053** [comment]
Понятно, что ничего не понятно)) статья про добавление mqtt в ha, а я имел ввиду поддержку его железкой)

**Comment by SCratORS** [comment]
Это статья говорит о том, что к конфиге прошивки надо указать адрес, логин, пароль брокера mqtt и все.
Просто сама система ESPHome нативно используетмя в HA.

**Comment by Tehnik053** [comment]
Я совсем не разбираюсь в НА и пользуюсь другой системой умного дома. Т.е. мне не получится связать их по mqtt?

**Comment by SCratORS** [comment]
Нет. 
Если пользователь хочет использовать нативно HA, то в конфиге прописывает пароль для доступа к API на HA.
Если пользователь хочет использовать MQTT на любых других системах умного дома, то в конфиге прописываются адрес,логин,пароль для доступа к MQTT сервера.

**Comment by Tehnik053** [comment]
Немного почитал про esphome, вроде пришло понимание. Спасибо буду пробовать.

**Comment by Tehnik053** [comment]
Извиняюсь за глупые вопросы но очень хочется воплотить данный проект у себя. Насколько я понял, для первоначальной прошивки нужен Линукс или НА? Под виндовс можно как то провернуть данные действия? Гугл отправляет на статьи где прошивается либо через НА либо из под Линукс. Попробовал поставить портативную версию НА под Винду, но интеграция ESPHome  в ней не устанавливается.

**Comment by SCratORS** [comment]
Установка и настройка ESPHome - это вопросы не этого проекта. Есть вопросы - Спрашивай на профильных сайтах.
Установка ESPHome 
1. Установи python
2. Установи pip3
3. Установи ESPHome
Линукс тут не обязателен.
