### ISSUE TITLE
Размышления о перспективе

### ISSUE THREAD

**Issue by exrector** [SCratORS/SmartIntercom#21]
Отличный проект. Замечательная аппаратная база. Но маркетинг никакой. Ваш продукт (а вам хотелось бы продавать готовый) покупает 1% тех сумасшедших, кто держит дома запущенный сервер для элементарных операций. 90% людей не знают даже как управиться с Алисой. Поэтому обычному человеку нужно что-то простое и легко (прикрутить пару винтов)инсталлируемое.. Поэтому я настаиваю на прямой интеграции в HomeKit/matter, если вы хотите, чтобы в каждом доме был ваш девайс. Благо на GitHub довольно много очень компактных интеграций. HAA? Homebridge? Да кому это надо? Вот этим двум с половиной ваших подписчиков… Это не бизнес модель. Я подчеркиваю, проект очень хорош с аппаратной стороны. Большая работа, вызывающая большое уважение. Сделайте «коробочку» с  винтовыми контакторами, чтобы любой смог подключить в разрыв между трубкой и дверью, добавить кодом в HomeKit - профит. Просто вдумайтесь - держать дома сервак, чтобы смотреть температуру и выключать/включать лампочки. Это безумие. Поэтому «бум» всего этого идиотизма сошел на нет и продержался довольно недолго. Благодаря тому же matter все, наконец-то приходит в нормальное русло с одним единственным хабом.

**Comment by SCratORS** [comment]
Спасибо Вам, за ваши идеи =)
Мне есть что вам ответить.
1. Что касается тех 90% кто не знает что такое HA или не хочет и тд. Тут стоит отметить, что без сервера устройство по определению не сможет взаимодействовать с той же Алисой, а значит нужен сторонний сервер, раз своего у "Вас" допустим нету. Бесплатно, разумеется никто его не даст. И поэтому стоимость его использования будет включена в стоимость продукта. Так или иначе, мне удалось наладить сотрудничество с ребятами из Swiitch, у них есть нужная инфраструктура. Поэтому, если Вам нужно просто решение из коробки (да, подороже, причины я назвал) - пожалуйста: https://shop.swiitch.ru/swiitch_domofon . Более того, используя устройство через них, можно добавить устройство в HomeKit. Так что да, это всё уже есть. Кстати купить устройство можно не только в их магазине, но и на Ozon https://ozon.ru/t/qe2qM5Y . Те кто читают наш телеграмм чат - уже давненько все это знают =) .
2. А вот с matter пока есть трудности. Да, я уже пробовал создать прошивку под него. И она даже работает и звук удалось сделать, но на текущий момент, matter не поддерживает нужные мне сущности управления и не дает возможности дать им человеческие названия. То есть всё, что мне удалось - это после подключения устройства к matter серверу, я вижу десяток даже не простых свитчей, а сущностей "ligth" и названия у них light1, light2 и тд. попробуй угадай, что за что отвечает. Тут вопрос пока в подвешенном состоянии. Но я более чем уверен, что когда matter сможет дать мне то, что мне нужно, чтобы не стыдно было выкатывать прошивку в массы - всё будет, всё в переди.
