### ISSUE TITLE
Не компилиться под Windows

### ISSUE THREAD

**Issue by NikolayKash** [SCratORS/SmartIntercom#4]
Нужно удалить пробелы, чтобы было так ESP8266Audio@1.9.1  или убрать версию вообще.

https://github.com/SCratORS/SmartIntercom/blob/0b589c70655f4b69d300d86fc40a0e4b2fa2d615/ESPHome/smartintercom_e8db849c6ee5.yaml#L35

ошибка при компиляции такая 

```
LibraryManager: Installing id=1964 @  1.9.1
UndefinedPackageVersion: Could not find a version that satisfies the requirement ' 1.9.1' for your system 'windows_amd64':
  File "C:\Users\nikol\AppData\Local\Programs\Python\Python39\Lib\site-packages\platformio\builder\main.py", line 168:

```

**Comment by SCratORS** [comment]
Fix
