### ISSUE TITLE
ESPAudio.h dependency issues

### ISSUE THREAD

**Issue by LuckyCoders** [SCratORS/SmartIntercom#5]
*********************************************************************************
* Looking for AudioFileSourceLittleFS.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AudioFileSourceLittleFS.h"
* Web  > https://platformio.org/lib/search?query=header:AudioFileSourceLittleFS.h
*
*********************************************************************************

**Comment by SCratORS** [comment]
No compilation errors were found. Try cleaning the compiled files and rebuilding the project.
Use files from the repository. Not out of release.
